//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommersShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsProduct
    {
        public int DetailsID { get; set; }
        public int AvailableQuantity { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int ProductReview { get; set; }
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public int LatestID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual LatestProduct LatestProduct { get; set; }
        public virtual TopProduct TopProduct { get; set; }
    }
}
